services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql_tunning
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  postgresql:
    image: postgres:16.8
    restart: always
    shm_size: 128mb
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

volumes:
  mysql_data:
